version: '3'

services:
  dbc-parser:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbc-parser
    ports:
      - "5002:80"
    restart: unless-stopped
    # volumes:
    #   - ./data:/usr/share/nginx/html/data
    networks:
      - dbc-network

networks:
  dbc-network:
    driver: bridge